[package]
name = "maelstrom-rust"
version = "0.1.0"
authors = ["Stephen Adams <stephenadams.minn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
lazy_static = "1.4.0"